//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThpK22CNT3Lession10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThpAccount
    {
        public int ThpID { get; set; }
        public string ThpUserName { get; set; }
        public string ThpPassword { get; set; }
        public string ThpFullName { get; set; }
        public string ThpEmail { get; set; }
        public string ThpPhone { get; set; }
        public Nullable<bool> ThpActive { get; set; }
    }
}
